version: "3.9"
#version: "3.3"
services:
  proxy:
    image: envoyproxy/envoy-alpine:v1.14.1
    environment:
      NODE_ENV: development
      loglevel: debug
    ports:
      - 8081:8081
      - 9900:9900
    networks:
      - envoymesh
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    restart: always
      
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    networks:
      - envoymesh
    restart: always

  register:
    container_name: register
    build: ./register
    ports:
      - "5001:5001"
    networks:
      - envoymesh
    restart: always

  classlist:
    container_name: classlist
    build: ./classlist
    ports:
      - "5002:5002"
    networks:
      - envoymesh
    restart: always

  cart:
    container_name: cart
    build: ./cart
    ports:
      - "5003:5003"
    networks:
      - envoymesh
    restart: always

  prof:
    container_name: prof
    build: ./prof
    ports:
      - "5004:5004"
    networks:
      - envoymesh
    restart: always
  
  mongodb-register:
    container_name: register_db
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    networks:
      - envoymesh
    volumes:
      - ./data/register/:/data/db
  mongodb-classlist:
    container_name: classlist_db
    image: mongo
    ports:
      - "27018:27017"
    restart: always
    networks:
      - envoymesh
    volumes:
      - ./data/classlist:/data/db
  mongodb-cart:
    container_name: cart_db
    image: mongo
    ports:
      - "27019:27017"
    restart: always
    networks:
      - envoymesh
    volumes:
      - ./data/cart:/data/db
  mongodb-prof:
    container_name: prof_db
    image: mongo
    ports:
      - "27020:27017"
    restart: always
    networks:
      - envoymesh
    volumes:
      - ./data/prof:/data/db

networks:
  envoymesh: {}
      