# prof_list = ["https://www.ratemyprofessors.com/ShowRatings.jsp?tid=2343388",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=1582680"]
# prof_list = ["https://www.ratemyprofessors.com/ShowRatings.jsp?tid=2343388"]
prof_list = ["https://www.ratemyprofessors.com/ShowRatings.jsp?tid=1582680"]
# prof_list = ["https://www.ratemyprofessors.com/ShowRatings.jsp?tid=182251",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=1908365",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=2410214",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=1987186",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=2312627",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=132578",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=1825700",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=653625",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=1005365",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=2478003",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=478261",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=766959",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=1582682",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=2476117",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=2343388",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=2180660",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=181787",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=132604",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=2630481",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=2040799",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=1582680",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=1902534",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=2576884",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=2317229",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=594443",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=260180",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=1890683",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=1136448",
# "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=270549"]
